import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { Download, Printer } from 'lucide-react';

import { prisma } from '@/lib/db';
import { requireTenant } from '@/lib/tenant';
import { can } from '@/lib/auth/rbac';
import { parseJson } from '@/lib/json';
import type { ReportPayload } from '@/lib/reports';
import {
  ACTION_STATUS_META,
  AUDIT_TYPE_LABELS,
  REQUIREMENT_STATUS_META,
  RISK_LEVEL_META,
  SEVERITY_META,
  type ActionStatus,
  type AuditType,
  type RequirementStatus,
  type RiskLevel,
  type Severity,
} from '@/lib/enums';
import { PageHeader } from '@/components/ui/primitives';
import { Badge } from '@/components/ui/badge';
import { SubmitButton } from '@/components/ui/form';
import { ReadinessRing } from '@/components/ui/readiness';
import { formatDate, formatDateTime, truncate } from '@/lib/utils';
import { deleteReportAction } from '../actions';
import { PrintButton } from './print-button';

export const metadata: Metadata = { title: 'Report' };

export default async function ReportDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const tenant = await requireTenant();
  const { id } = await params;

  const report = await prisma.auditReport.findFirst({
    where: { id, orgId: tenant.orgId },
    include: { generatedBy: { select: { name: true } } },
  });
  if (!report) notFound();

  const data = parseJson<ReportPayload | null>(report.data, null);
  if (!data) notFound();

  return (
    <div className="mx-auto max-w-4xl">
      <div className="print:hidden">
        <PageHeader
          title={report.title}
          description={`Generated by ${report.generatedBy.name} on ${formatDateTime(report.createdAt)}`}
          breadcrumb={[
            { label: 'Reports', href: `/app/reports?project=${report.projectId}` },
            { label: truncate(report.title, 40) },
          ]}
          action={
            <>
              <a href={`/api/reports/${report.id}/pdf`} className="btn-secondary btn-md">
                <Download className="h-4 w-4" aria-hidden />
                Download PDF
              </a>
              <PrintButton />
              {can(tenant.role, 'report:generate') && (
                <form action={deleteReportAction}>
                  <input type="hidden" name="reportId" value={report.id} />
                  <SubmitButton variant="ghost" pendingLabel="Deleting…">
                    Delete
                  </SubmitButton>
                </form>
              )}
            </>
          }
        />
      </div>

      <article className="card prose-report p-8 print:border-0 print:p-0 print:shadow-none">
        {/* Letterhead */}
        <header className="border-b border-ink-200 pb-6">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <p className="text-[12px] font-semibold uppercase tracking-[0.14em] text-kelp-700">
                Audit preparation report
              </p>
              <h1 className="mt-1.5 text-[24px] font-bold leading-tight text-ink-900">{data.organization.name}</h1>
              <p className="mt-1 text-[14px] text-ink-600">
                {data.project.name} · {data.project.framework} v{data.project.frameworkVersion}
              </p>
            </div>
            <div className="text-right text-[12.5px] text-ink-500">
              <p>Generated {formatDateTime(data.generatedAt)}</p>
              {data.project.auditDate && <p className="mt-0.5">Audit date {formatDate(data.project.auditDate)}</p>}
              {data.project.daysUntilAudit !== null && (
                <p className="mt-0.5 font-semibold text-ink-800">
                  {data.project.daysUntilAudit >= 0
                    ? `${data.project.daysUntilAudit} days remaining`
                    : `${Math.abs(data.project.daysUntilAudit)} days past`}
                </p>
              )}
            </div>
          </div>
        </header>

        {/* Headline */}
        <section className="flex flex-col items-center gap-6 border-b border-ink-200 py-8 sm:flex-row sm:items-center sm:justify-between">
          <ReadinessRing
            score={data.readiness.score}
            size={150}
            strokeWidth={11}
            riskLevel={data.readiness.riskLevel as RiskLevel}
          />
          <dl className="grid flex-1 grid-cols-2 gap-x-8 gap-y-3 sm:grid-cols-3">
            {[
              ['Audit type', AUDIT_TYPE_LABELS[data.project.auditType as AuditType] ?? data.project.auditType],
              ['Requirements', String(data.readiness.total)],
              ['Assessed', `${data.readiness.assessed} of ${data.readiness.total}`],
              ['Evidence items', String(data.evidence.total)],
              ['Open actions', String(data.actions.open)],
              ['Overdue actions', String(data.actions.overdue)],
            ].map(([term, value]) => (
              <div key={term}>
                <dt className="text-[11.5px] font-medium uppercase tracking-wide text-ink-500">{term}</dt>
                <dd className="tnum mt-0.5 text-[15px] font-semibold text-ink-900">{value}</dd>
              </div>
            ))}
          </dl>
        </section>

        {/* Requirement status */}
        <section className="border-b border-ink-200 py-7">
          <h2>Requirement status</h2>
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
            {(Object.keys(data.readiness.counts) as RequirementStatus[]).map((status) => (
              <div key={status} className="rounded-lg border border-ink-200 px-4 py-3">
                <div className="flex items-center gap-1.5">
                  <span
                    className={`h-2 w-2 rounded-full ${
                      REQUIREMENT_STATUS_META[status].tone === 'strong'
                        ? 'bg-strong-500'
                        : REQUIREMENT_STATUS_META[status].tone === 'caution'
                          ? 'bg-caution-500'
                          : REQUIREMENT_STATUS_META[status].tone === 'risk'
                            ? 'bg-risk-500'
                            : 'bg-ink-300'
                    }`}
                    aria-hidden
                  />
                  <span className="text-[11.5px] font-medium uppercase tracking-wide text-ink-500">
                    {REQUIREMENT_STATUS_META[status].label}
                  </span>
                </div>
                <div className="tnum mt-1 text-[20px] font-bold text-ink-900">
                  {data.readiness.counts[status] ?? 0}
                </div>
              </div>
            ))}
          </div>
          <p className="mt-4 text-[13px] leading-relaxed text-ink-600">
            Readiness is weighted by requirement importance and counts only evidence a person has approved.{' '}
            {data.links.pending > 0 &&
              `${data.links.pending} suggested evidence match${data.links.pending === 1 ? '' : 'es'} were awaiting human review when this report was generated and are excluded from the score.`}
          </p>
        </section>

        {/* Evidence */}
        <section className="border-b border-ink-200 py-7">
          <h2>Evidence statistics</h2>
          <table className="w-full text-[13.5px]">
            <tbody className="divide-y divide-ink-100">
              {[
                ['Total evidence items', data.evidence.total],
                ['Accepted', data.evidence.accepted],
                ['Awaiting review', data.evidence.pendingReview],
                ['Expired', data.evidence.expired],
                ['Expiring within 60 days', data.evidence.expiringSoon],
                ['Requirement links — approved', data.links.approved],
                ['Requirement links — awaiting review', data.links.pending],
                ['Requirement links — rejected', data.links.rejected],
              ].map(([label, value]) => (
                <tr key={String(label)}>
                  <td className="py-2 text-ink-600">{label}</td>
                  <td className="tnum py-2 text-right font-semibold text-ink-900">{value}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        {/* Gaps */}
        <section className="border-b border-ink-200 py-7">
          <h2>Major gaps and high-risk items</h2>
          {data.majorGaps.length === 0 ? (
            <p>No open gaps were recorded on this project when the report was generated.</p>
          ) : (
            <ol className="space-y-3">
              {data.majorGaps.slice(0, 25).map((gap, index) => (
                <li key={index} className="rounded-lg border border-ink-200 p-4">
                  <div className="flex flex-wrap items-center gap-2">
                    <Badge tone={SEVERITY_META[gap.severity as Severity].tone} size="sm">
                      {SEVERITY_META[gap.severity as Severity].label}
                    </Badge>
                    <span className="text-[13.5px] font-semibold text-ink-900">{gap.title}</span>
                  </div>
                  <p className="mt-1.5 text-[13px] leading-relaxed text-ink-600">{gap.description}</p>
                  <p className="mt-1.5 text-[12px] text-ink-500">
                    {gap.typeLabel}
                    {gap.requirement && ` · ${gap.requirement}`}
                    {gap.owner && ` · owner ${gap.owner}`}
                    {gap.dueDate && ` · due ${formatDate(gap.dueDate)}`}
                  </p>
                </li>
              ))}
            </ol>
          )}
          {data.majorGaps.length > 25 && (
            <p className="mt-3 text-[12.5px] text-ink-500">
              {data.majorGaps.length - 25} further gap(s) omitted from this listing.
            </p>
          )}
        </section>

        {/* Actions */}
        <section className="border-b border-ink-200 py-7">
          <h2>Open actions</h2>
          {data.openActions.length === 0 ? (
            <p>No open actions were recorded on this project when the report was generated.</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full min-w-[520px] text-[13px]">
                <thead>
                  <tr className="border-b border-ink-200 text-left text-[11.5px] uppercase tracking-wide text-ink-500">
                    <th className="py-2 pr-3 font-medium">Ref</th>
                    <th className="py-2 pr-3 font-medium">Action</th>
                    <th className="py-2 pr-3 font-medium">Owner</th>
                    <th className="py-2 pr-3 font-medium">Due</th>
                    <th className="py-2 font-medium">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-ink-100">
                  {data.openActions.map((action) => (
                    <tr key={action.reference}>
                      <td className="py-2 pr-3 font-mono text-[11.5px] text-ink-600">{action.reference}</td>
                      <td className="py-2 pr-3 text-ink-800">{action.title}</td>
                      <td className="py-2 pr-3 text-ink-600">{action.owner ?? '—'}</td>
                      <td className={`py-2 pr-3 ${action.overdue ? 'font-semibold text-risk-600' : 'text-ink-600'}`}>
                        {action.dueDate ? formatDate(action.dueDate) : '—'}
                        {action.overdue && ' (overdue)'}
                      </td>
                      <td className="py-2 text-ink-600">
                        {ACTION_STATUS_META[action.status as ActionStatus]?.label ?? action.status}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </section>

        {/* Requirements needing review */}
        <section className="border-b border-ink-200 py-7">
          <h2>Requirements needing attention</h2>
          {data.requirementsNeedingReview.length === 0 ? (
            <p>Every requirement in scope was satisfied or marked not applicable.</p>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full min-w-[480px] text-[13px]">
                <thead>
                  <tr className="border-b border-ink-200 text-left text-[11.5px] uppercase tracking-wide text-ink-500">
                    <th className="py-2 pr-3 font-medium">ID</th>
                    <th className="py-2 pr-3 font-medium">Requirement</th>
                    <th className="py-2 pr-3 font-medium">Owner</th>
                    <th className="py-2 font-medium">Status</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-ink-100">
                  {data.requirementsNeedingReview.map((requirement) => (
                    <tr key={requirement.identifier}>
                      <td className="py-2 pr-3 font-mono text-[11.5px] text-ink-600">{requirement.identifier}</td>
                      <td className="py-2 pr-3 text-ink-800">{requirement.title}</td>
                      <td className="py-2 pr-3 text-ink-600">{requirement.owner ?? '—'}</td>
                      <td className="py-2 text-ink-600">
                        {REQUIREMENT_STATUS_META[requirement.status as RequirementStatus]?.label ?? requirement.status}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </section>

        {/* Recommendations */}
        <section className="border-b border-ink-200 py-7">
          <h2>Recommendations</h2>
          <ol className="space-y-2.5">
            {data.recommendations.map((recommendation, index) => (
              <li key={index} className="flex gap-3 text-[13.5px] leading-relaxed text-ink-700">
                <span className="tnum shrink-0 font-semibold text-ink-400">{index + 1}.</span>
                {recommendation}
              </li>
            ))}
          </ol>
        </section>

        {/* Risk + disclaimer */}
        <footer className="pt-7">
          <div className="flex flex-wrap items-center gap-3">
            <span className="text-[12px] font-semibold uppercase tracking-wide text-ink-500">Internal audit risk</span>
            <Badge tone={RISK_LEVEL_META[data.readiness.riskLevel as RiskLevel].tone} dot>
              {RISK_LEVEL_META[data.readiness.riskLevel as RiskLevel].label}
            </Badge>
            <span className="text-[12.5px] text-ink-500">
              Preparedness indicator only — not a prediction of an audit outcome.
            </span>
          </div>

          <p className="mt-5 rounded-lg border border-ink-200 bg-ink-50 p-4 text-[12px] leading-relaxed text-ink-600">
            {data.disclaimer}
          </p>

          <p className="mt-3 text-[11.5px] text-ink-400">
            Analysis engine: {data.aiProvider.name} ({data.aiProvider.model}).{' '}
            {data.aiProvider.live
              ? 'AI-assisted assessments in this report were produced by a live model and reviewed only where a person explicitly approved them.'
              : 'AI-assisted assessments in this report were produced by the deterministic built-in engine.'}
          </p>
        </footer>
      </article>
    </div>
  );
}
